apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: puckel/docker-airflow
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
